default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: kolba
  password:
  timeout: 5000

development:
  <<: *default
  database: sbe

test:
  <<: *default
  database: sbe-test

production:
  <<: *default
  database: sbe-prod
